export const GET_PETS = 'GET_PETS';
export const GET_PETS_FAILURE = 'GET_PETS_FAILURE';
export const GET_PETS_SUCCESS = 'GET_PETS_SUCCESS';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const UPDATE_TYPE_PREFERENCE = 'UPDATE_TYPE_PREFERENCE';
export const UPDATE_MAX_AGE = 'UPDATE_MAX_AGE';
export const UPDATE_MIN_AGE = 'UPDATE_MIN_AGE';

export const SAVE_PET = 'SAVE_PET';
export const SAVE_PET_PREFERENCE_CHANGE = 'SAVE_PET_PREFERENCE_CHANGE';


